### ISSUE TITLE
Like, remove like, check like song.

### ISSUE THREAD

**Issue by saraguilleng** [UNIZAR-30226-2020-04/back-end#26]
funiones para dar like y quitar el like a una cancion, y comprobar si te gusta una cancion

**Comment by adrigaarcia** [comment]
Hecho sin probar, hecho como el follow de playlist, relacion @ManyToMany con Usuario como owner. Funciones add, remove y find.

**Comment by adrigaarcia** [comment]
Al cambiar la relación por las claves compuestas, necesita actualización.

**Comment by adrigaarcia** [comment]
"/likeSong"				Usuario da me gusta a una cancion

"/unLikeSong"			Usuario deja de gustar una cancion
	
"/checkLike"			Comprobar si a un usuario le gusta una cancion

"/listLikes"			Listar canciones que le gustan a un usuario	

"/listAlbumsLikes"		Listar albumes de las canciones que le gustan a un usuario

"/listUsersLikes"		Listar usuarios creadores de las canciones que le gustan a un usuario
