### ISSUE TITLE
Funciones para la sección biblioteca. 

### ISSUE THREAD

**Issue by saraguilleng** [UNIZAR-30226-2020-04/back-end#27]
Función que devuelva las playlist que sigues.
Función que devuelva los albums de canciones que te gustan.
Función que devuelva los usuarios de las canciones que te gustan.
Función que devuelva los podcast que sigues.

**Comment by adrigaarcia** [comment]
Hecho:
Playlists que sigues
Podcasts a los que estás suscrito
Usuarios owners de las canciones que te gustan
Albumes que contienen las canciones que te gustan
Canciones que te gustan

**Comment by adrigaarcia** [comment]
Al cambiar la relación por las claves compuestas, necesita actualización.

**Comment by adrigaarcia** [comment]
"/subscribeUser"	Suscribir usuario a un podcast

"/unsubscribeUser"	Dessuscribir usuario de un podcast

"/checkSubscription"	Comprobar si un usuario está suscrito a un podcast

"/listSubscriptions"	Listar podcast a los que un usuario esta suscrito

"/followPlayList"		Usuario comienza a seguir playlist

"/unfollowPlayList"		Usuario deja de seguir playlist

"/checkFollow"			Comprobar si un usuario sigue una playlist

"/listFollows"			Listar playlists que sigue un usuario

"/likeSong"				Usuario da me gusta a una cancion

"/unLikeSong"			Usuario deja de gustar una cancion
	
"/checkLike"			Comprobar si a un usuario le gusta una cancion

"/listLikes"			Listar canciones que le gustan a un usuario	

"/listAlbumsLikes"		Listar albumes de las canciones que le gustan a un usuario

"/listUsersLikes"		Listar usuarios creadores de las canciones que le gustan a un usuario
