### ISSUE TITLE
Lista "Me gusta" de un usuario

### ISSUE THREAD

**Issue by rubenDTD** [UNIZAR-30226-2020-04/back-end#28]
Un usuario tiene una lista predeterminada de canciones que le gustan, así que tiene que existir de alguna forma sin que el usuario la cree, ya sea al registrar el usuario (creo que esto es lo más cómodo) o la primera vez que le de me gusta a una canción.

**Comment by adrigaarcia** [comment]
La lista existe como relacion @ManyToMany entre Usuario y Reproduccion. Se crea cuando se da me gusta por primera vez a una canción.

**Comment by adrigaarcia** [comment]
Al cambiar la relación por las claves compuestas, necesita actualización.

**Comment by adrigaarcia** [comment]
"/subscribeUser"	Suscribir usuario a un podcast

"/unsubscribeUser"	Dessuscribir usuario de un podcast

"/checkSubscription"	Comprobar si un usuario está suscrito a un podcast

"/listSubscriptions"	Listar podcast a los que un usuario esta suscrito

"/followPlayList"		Usuario comienza a seguir playlist

"/unfollowPlayList"		Usuario deja de seguir playlist

"/checkFollow"			Comprobar si un usuario sigue una playlist

"/listFollows"			Listar playlists que sigue un usuario

"/likeSong"				Usuario da me gusta a una cancion

"/unLikeSong"			Usuario deja de gustar una cancion
	
"/checkLike"			Comprobar si a un usuario le gusta una cancion

"/listLikes"			Listar canciones que le gustan a un usuario	

"/listAlbumsLikes"		Listar albumes de las canciones que le gustan a un usuario

"/listUsersLikes"		Listar usuarios creadores de las canciones que le gustan a un usuario
